[settings]
  ID = "porter-vanity"

[build]
  publish = "vanity/public"
  command = "make"

[build.environment]
  HUGO_VERSION = "0.53"

[context.branch-deploy]
  command = "make BASEURL_FLAG=\"-b $DEPLOY_PRIME_URL\"/"
  
[context.deploy-preview]
  command = "make BASEURL_FLAG=\"-b $DEPLOY_PRIME_URL\"/"